"""created_time fixed

Revision ID: 617717180157
Revises: b51ab90ea369
Create Date: 2021-10-03 10:56:26.340234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617717180157'
down_revision = 'b51ab90ea369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_post')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('created_time')

    op.create_table('_alembic_tmp_post',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=25), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=25), nullable=True),
    sa.Column('created_time', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
